server:
  apiurl: http://bjsuma.bo2go.home/rpc/api
  username: bjin
  password: suse1234

listmethod1:
  methodname: systemgroup.listActiveSystemsInGroup
  input_map:
    1_systemGroupName: test2
       
  out_variablenames:  
    - id


listmethod2:
  methodname: system.getRelevantErrata
  input_map:
    1_serverid: listmethod1.id

  out_variablenames: 
    - id
    - advisory_synopsis
    - advisory_name
    - advisory_type

finalmethod:
  methodname: system.scheduleApplyErrata
  options:
    meth2_depend_meth1: true
  input_map:
    1_serverid: listmethod1.id
    2_errataId: listmethod2.array.id
    3_earliestOccurrence: datetime.2020-08-23T09:45:00

  out_variablenames: 
    - actionId
    
