server:
  apiurl: http://bjsuma.bo2go.home/rpc/api
  username: bjin
  password: suse1234

listmethod1:
  methodname: systemgroup.listActiveSystemsInGroup
  input_map:
    1_systemGroupName: test2
       
  out_variablenames:  
    - id


listmethod2:
  methodname: system.getRelevantErrataByType
  input_map:
    1_serverid: listmethod1.id
    2_advisoryType: "Security Advisory"

  out_variablenames: 
    - id
    - advisory_synopsis
    - advisory_name

finalmethod:
  methodname: system.scheduleApplyErrata
  input_map:
    1_serverid: listmethod1.array.id
    2_errataId: listmethod2.array.id
    3_earliestOccurrence: datetime.2020-07-30T21:30:00
    4_allowModules: bool.true

  out_variablenames: 
    - actionId
    
